trainer:
  max_epochs: 31
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      resume: allow
      project: "eomt"
      name: "ade20k_semantic_eomt_large_512"
model:
  class_path: training.mask_classification_semantic.MaskClassificationSemantic
  init_args:
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [6520, 13040, 19560, 26080]
    attn_mask_annealing_end_steps: [13040, 19560, 26080, 32600]
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 100
        encoder:
          class_path: models.vit.ViT
data:
  class_path: datasets.ade20k_semantic.ADE20KSemantic